### ISSUE TITLE
safe retrieval fails on nethermind

### ISSUE THREAD

**Issue by svanegmond** [gnosis/gnosis-py#205] opened 2022-03-09 21:44 UTC
The implementation of retrieve_all_info makes an Eth RPC call to specific functions to get nonce, threshold, owners, etc.

To do this it provides the safe address as the 'from'. This is not accepted on the Nethermind Eth client. 

To reproduce:

Here is an example of posting a call to VERSION() on the Rinkeby network:

```
nethermind> node.switch('https://rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161')                                                                                           
nethermind>  eth.call({"to": "0xe8b541b0E9a3981E3aC0e324B987940c4eF4069B", "data": "0xffa1ad74", "from": "0xe8b541b0E9a3981E3aC0e324B987940c4eF4069B"}, "latest")                  
"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000005312e332e30000000000000000000000000000000000000000000000000000000"
```

'312e332e30' is ASCII for "1.3.0", the contract version. 

Trying the same kind of call against a Nethermind client is rejected (see [source](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs), line 191) however it works fine when provided any other kind of address, even 0x0.

```
nethermind> node.switch('https://rpc.testnet.shyft.network/')
nethermind> eth.call({"to": "0xc5847FcB4A4270DC77800a1487Ce29cB9922bD41", "data": "0xffa1ad74", "from": "0xc5847FcB4A4270DC77800a1487Ce29cB9922bD41"}, "latest")                   
VM execution error. | sender has deployed code

nethermind> eth.call({"to": "0xc5847FcB4A4270DC77800a1487Ce29cB9922bD41", "data": "0xffa1ad74", "from": "0x0000000000000000000000000000000000000000"}, "latest")                   
"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000005312e332e30000000000000000000000000000000000000000000000000000000"
```

**Comment by svanegmond** [comment] 2022-03-10 05:39
also, needs exception reporting, at least an error log

**Comment by Uxio0** [comment] 2022-03-11 11:00
Hi @svanegmond , I cannot reproduce the error with my nethermind node, it's working well (v1.11.7)

**Comment by svanegmond** [comment] 2022-03-11 17:19
Hi, 
The code responsible was introduced with 1.11.5, so that's odd.  Ah, it was reverted in 1.11.7, then re-enabled in December.

The commit log points to https://eips.ethereum.org/EIPS/eip-3607 whose very name is "Reject transactions from senders with deployed code"

If you upgrade to a nethermind in 1.12 you will find this bug.

**Comment by Uxio0** [comment] 2022-03-14 11:00
Hi, I'm Nethermind last available version and I cannot reproduce, I don't get any error calling:

```
{"jsonrpc":"2.0","method":"eth_call","params":[{"to": "0xc5847FcB4A4270DC77800a1487Ce29cB9922bD41", "data": "0xffa1ad74", "from": "0xc5847FcB4A4270DC77800a1487Ce29cB9922bD41"}, "latest"],"id":1}
```

**Comment by svanegmond** [comment] 2022-03-15 18:51
Well, this is upsetting.  

When I filed this bug, I could not get the tx gateway to provide safe's details, and it took me a very long time to trace it to this.  

Now when I test the same node as I did above:

```
nethermind> node.switch('https://rpc.testnet.shyft.network')                    

nethermind> eth.call({"to": "0xc5847FcB4A4270DC77800a1487Ce29cB9922bD41", "data": "0xffa1ad74", "from": "0xc5847FcB4A4270DC77800a1487Ce29cB9922bD41"}, "latest")
"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000005312e332e30000000000000000000000000000000000000000000000000000000"
```

This produced 'sender has deployed code' before, and my safe tx gateway produced a safe description with no owner, nonce, threshold, or version (the 4 things that are retrieved over rpc).

I tried with every nethermind version since 1.12.5 and "sender has deployed code" shows up on 1.11.5, 1.11.6. Does not on 1.11.7 and newer. Reading the source, I can't understand why.

I guess you can kill this bug until I can cause it to happen again.  I am certain it will break again eventually:  EIP 3607 is final, and is being implemented (allegedly already in geth). My fix was to change safe.py line 859:

```
<                from_address=self.address,
>                from_address=NULL_ADDRESS,
```

**Comment by Uxio0** [comment] 2022-03-16 10:57
We had issues with that on the past, and that's why we set `from_address=self.address` when using `eth_call`. Having to make the library compatible with geth, nethermind, erigon and OpenEthereum (among others) is not really easy 😉 .

Regarding https://eips.ethereum.org/EIPS/eip-3607, `Clients might choose to disable this rule for RPC calls like eth_call and eth_estimateGas as some Multi-Sig contracts use these calls to create transactions as if they originated from the multisig contract itself.`. That's precisely what we are doing and it will break some of our logic, so I wish they don't change that 😬 .

Thanks for bringing up this issue, I will close it for now. If that happens again please comment here and I will reopen it.

**Closed** 2022-03-17 15:52 UTC
Labels: bug
